// <auto-generated />
namespace PhotoServer2.App_Archicture.Services.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AddCreateAtAndCreatedByColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCreateAtAndCreatedByColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201312101708038_AddCreateAtAndCreatedByColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
